"""update dateOfBirth type

Revision ID: 10d69ae879d5
Revises: 623975312666
Create Date: 2024-11-20 07:54:04.276927

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10d69ae879d5'
down_revision: Union[str, None] = '623975312666'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('students', 'dateOfBirth',
                    nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('students', 'dateOfBirth',
                    nullable=True)
    # ### end Alembic commands ###
