"""test

Revision ID: 46b4940e5fe9
Revises: f369d334c2e9
Create Date: 2024-11-20 07:36:31.186065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46b4940e5fe9'
down_revision: Union[str, None] = 'f369d334c2e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('students', 'firstName',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('students', 'lastName',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('students', 'dateOfBirth',
               existing_type=sa.DATE(),
               type_=sa.String(),
               nullable=True)
    op.create_index(op.f('ix_students_studentId'), 'students', ['studentId'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_students_studentId'), table_name='students')
    op.alter_column('students', 'dateOfBirth',
               existing_type=sa.String(),
               type_=sa.DATE(),
               nullable=False)
    op.alter_column('students', 'lastName',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('students', 'firstName',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
