"""update dateOfBirth type

Revision ID: 600c6281d203
Revises: ac177d49f90d
Create Date: 2024-11-20 08:08:45.791336

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '600c6281d203'
down_revision: Union[str, None] = 'ac177d49f90d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column(
        'dateOfBirth', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'dateOfBirth')
    # ### end Alembic commands ###
