"""update db

Revision ID: 623975312666
Revises: 46b4940e5fe9
Create Date: 2024-11-20 07:46:28.822080

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '623975312666'
down_revision: Union[str, None] = '46b4940e5fe9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_classes_classId'),
                    'classes', ['classId'], unique=False)
    op.create_index(op.f('ix_classes_level'),
                    'classes', ['level'], unique=False)
    op.create_index(op.f('ix_classes_name'), 'classes', ['name'], unique=False)
    op.create_index(op.f('ix_courses_courseId'),
                    'courses', ['courseId'], unique=False)
    op.create_index(op.f('ix_courses_name'), 'courses', ['name'], unique=False)
    op.create_index(op.f('ix_registry_registryId'),
                    'registry', ['registryId'], unique=False)
    op.create_index(op.f('ix_registry_status'),
                    'registry', ['status'], unique=False)
    op.create_index(op.f('ix_student_courses_status'),
                    'student_courses', ['status'], unique=False)
    op.create_index(op.f('ix_student_courses_studentCoursesId'),
                    'student_courses', ['studentCoursesId'], unique=False)
    op.alter_column('students', 'firstName',
                    existing_type=sa.VARCHAR(),
                    nullable=False)
    op.alter_column('students', 'lastName',
                    existing_type=sa.VARCHAR(),
                    nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('students', 'lastName',
                    existing_type=sa.VARCHAR(),
                    nullable=True)
    op.alter_column('students', 'firstName',
                    existing_type=sa.VARCHAR(),
                    nullable=True)
    op.drop_index(op.f('ix_student_courses_studentCoursesId'),
                  table_name='student_courses')
    op.drop_index(op.f('ix_student_courses_status'),
                  table_name='student_courses')
    op.drop_index(op.f('ix_registry_status'), table_name='registry')
    op.drop_index(op.f('ix_registry_registryId'), table_name='registry')
    op.drop_index(op.f('ix_courses_name'), table_name='courses')
    op.drop_index(op.f('ix_courses_courseId'), table_name='courses')
    op.drop_index(op.f('ix_classes_name'), table_name='classes')
    op.drop_index(op.f('ix_classes_level'), table_name='classes')
    op.drop_index(op.f('ix_classes_classId'), table_name='classes')
    # ### end Alembic commands ###
