"""Initial migration

Revision ID: 8162af8b62ce
Revises: 
Create Date: 2024-11-14 15:55:56.928555

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8162af8b62ce'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classes',
    sa.Column('classId', sa.UUID(), nullable=False),
    sa.Column('level', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('dateCreated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('lastUpdated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('classId')
    )
    op.create_table('courses',
    sa.Column('courseId', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('dateCreated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('lastUpdated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('courseId')
    )
    op.create_table('registry',
    sa.Column('registryId', sa.UUID(), nullable=False),
    sa.Column('studentId', sa.UUID(), nullable=False),
    sa.Column('classId', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('dateCreated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('lastUpdated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('registryId')
    )
    op.create_table('student_courses',
    sa.Column('studentCoursesId', sa.UUID(), nullable=False),
    sa.Column('studentId', sa.UUID(), nullable=False),
    sa.Column('courseId', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('dateCreated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('lastUpdated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('studentCoursesId')
    )
    op.create_table('students',
    sa.Column('studentId', sa.UUID(), nullable=False),
    sa.Column('firstName', sa.String(), nullable=False),
    sa.Column('otherNames', sa.String(), nullable=False),
    sa.Column('lastName', sa.String(), nullable=False),
    sa.Column('dateOfBirth', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('studentId')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('students')
    op.drop_table('student_courses')
    op.drop_table('registry')
    op.drop_table('courses')
    op.drop_table('classes')
    # ### end Alembic commands ###
