"""update dateOfBirth type

Revision ID: ac177d49f90d
Revises: 10d69ae879d5
Create Date: 2024-11-20 08:08:06.957474

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac177d49f90d'
down_revision: Union[str, None] = '10d69ae879d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'dateOfBirth')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('dateOfBirth', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
