"""update dateOfBirth type

Revision ID: d1b227f9d806
Revises: 600c6281d203
Create Date: 2024-11-20 08:11:03.291272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1b227f9d806'
down_revision: Union[str, None] = '600c6281d203'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('students', 'dateOfBirth',
               existing_type=sa.DATE(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('students', 'dateOfBirth',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###
