"""Made other names a nullable field

Revision ID: f369d334c2e9
Revises: 8162af8b62ce
Create Date: 2024-11-18 15:41:13.145139

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f369d334c2e9'
down_revision: Union[str, None] = '8162af8b62ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('students', 'otherNames',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('students', 'otherNames',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
